#!/bin/sh

lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer none \
  --archive-areas "main non-free-firmware" \
  --bootappend-live "boot=live components hostname=larp username=linux user-fullname='Linux LARP User'" \
  "${@}"
